### ISSUE TITLE
router - create a unit level fifo_arb TB.

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia#125]
No need to do anything fancy.
A simple simulation that can push to different FIFO & accept arbitration winner.
- have a "push fifo[I] task" that can write to fif_arb
- make sure the output field "next_tile_fifo_arb_id" is set correctly according to the current tile, next tile, final destination.
- make sure to use the "in_ready" as part of the arbitration scheme
- make sure to see the correct calculation of the next_tile_fifo_arb_id (north, south east, west)
- have coverage point to push back using the "out_ready" per fifo once is full.

**Comment by ShmuelSfez** [comment]
done.
