### ISSUE TITLE
cache - add in cache_pp options to test all or specific test

### ISSUE THREAD

**Issue by noamsabb** [amichai-bd/fpga_mafia#149]
Make cache_pp.py get args
- -all or no arg : run golden_trk check on all existing tests
- 'test name' : run golden_trk check for this specific test

**Comment by amichai-bd** [comment]
I think the cache_pp.py should be "simple" and "stupid" - meaning run on a single test only..
I want to tp be able to be called from the build - and the build will be calling it for every test it runs on the cache DUT.
