### ISSUE TITLE
BIG_CORE - create the duel port i_mem & d_mem for the FPGA synth

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia#161]
Make sure to match a behavioral model.

**Comment by amichai-bd** [comment]
@danielk532 - we did the FPGA side, please make sure to fix the simulation mem to be the same as the generated FPGA memory.
Once they have the exact same IO, we can remove the "SIM_ONLY" flag we added in the instance

**Comment by danielk532** [comment]
Done
