### ISSUE TITLE
Cache - add a new test that has B2B write hit, and a test with B2B Read Hit. (delay(0))

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia#179]
To get the hit, first, we must get the data from FM with a RD/WR miss - wait ~20 cycles, then we can start the B2B sequence

(Note - the PP checker wont work for B2B - first you must fix the #178 issue.)

**Comment by noamsabb** [comment]
Done
Tests names: 
    wr_b2b_hit
    rd_b2b_hit
