### ISSUE TITLE
Cache - write 2 test that will fail - need to exclude them from level0

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia#181]
1) Write 2 tests that will fail due to DUT not ready. (Example read after reading B2B same CL, when they miss, Example B2B RdAfter Rd different CL - should fail because we did not enable Stall, re-issue buffer, cancel, etc...)
2) write a level0 list that will run only the test that is currently passing. (See level0 reference in BIG_CORE)
3) modify the workflow so it will run only passing tests (Find the WORKFLOW under .github/workflow)

**Comment by noamsabb** [comment]
Done
Tests names: 
    rd_b2b_same_cl
    rd_b2b_diff_cl
