### ISSUE TITLE
router - add more complicated sequences to fifo_arb tests.

### ISSUE THREAD

**Issue by ShmuelSfez** [amichai-bd/fpga_mafia#183]
add tests:
1. simple test - 4 request for 4 fifo's (wait 3 cycles between each request).
2. parallel inputs test - 4 request for 4 fifo's (in parallel - no wait's), expecting for output B2B(back to back, outputs in each clock cycle).
3.  single fifo full BW test - one fifo 10 request B2B. expecting 10 outputs B2B.
4. all fifo's full BW test - testing the back pressure, 40 requests B2B in parallel to all FIFO's. make sure that the TB takes the full indication into considiration when trying to push new requests to the FIFO's.
important!! make sure that all data is out at the end.

**Comment by amichai-bd** [comment]
Update from @ShmuelSfez 
1 & 3 are submitted (Checker is enabled!!)
2 & 4 are WIP. (Still failing, see if checker has an error or the RTL)

**Comment by ShmuelSfez** [comment]
added all relevant test. plus added a test to check the Assertions in FIFO module.
