### ISSUE TITLE
fabric - create the mini_core_tile RTL + basic DUT tests

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia#221]
Please comment here on what you will try todo and ask here any questions

**Comment by amichai-bd** [comment]
Please leave the mini core interface dangling/strap to 0

In the TB we will drive the values using XMR - cross module reference

**Comment by ShmuelSfez** [comment]
Done' will be added in the pull to main. i would like to have an overview of the waves in order to get a better understanding of what exactly we want to achieve.
