### ISSUE TITLE
router - override the specific field in the in_<carrd>_req of the "next_tile_fifo_arb_id"

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia#225]
Note: this can be done in fifo arb output or in the FIFO arb input.

Maybe output makes more sense - but what ever you want.
For now, write a simple algorithm that can set the next tile according to the current TILE_ID and the destination (MSB of address)

Example:
Algorithm of "first go to row, then column"

0,0     0,1     0,2      0,3   ...
1,0     1,1     1,2      1,3   ...
2,0     2,1     2,2      2,3   ...
3,0     3,1     3,2      3,3   ...
...      ...        ...        ... 

Current TILE ID 3,3
Target Tile ID 5,2

5 is greater than 3, so you must first go south

Current TILE ID 3,3
Target Tile ID 3,1

3 is the correct row, need to got west to read from 3 to 1.

Please give some thought on the "LOCAL" when you choose is.

Please elaborate in this issue the LOCAL stuff.

**Comment by yeonatanPerelman** [comment]
I have a compiling problem:
the file: 'south_next_tile_fifo_arb' doesn't work.
I'm getting this error:
![image](https://user-images.githubusercontent.com/111231093/235081311-04176f1b-51e6-4a09-9b32-d174731f5ad1.png)

and in the 'hw_compile.log' I do not see the file:
![image](https://user-images.githubusercontent.com/111231093/235081763-e0cc30ff-509a-4179-bbbe-f306415eb701.png)
