### ISSUE TITLE
Cache - edit pipe stages 

### ISSUE THREAD

**Issue by noamsabb** [amichai-bd/fpga_mafia#230]
add dirty evict data to pipe stages tracker
it is coming from q3

**Comment by noamsabb** [comment]
@amichai-bd can you help me found/understand what data I need to add to the tracker, in q3 I have found only the same dirty_evict bit that we are already printing in the tracker through q2

**Comment by amichai-bd** [comment]
It's talking about the CL data - not the indication..
Just so it will be easier to debug the IO, so you can see what was the dirty evict data

**Comment by noamsabb** [comment]
So we want to print the data of the dirty evict, meaning the data that is going to be evicted (overwrite) ?

**Comment by amichai-bd** [comment]
The data that we want to sent to FM

**Comment by amichai-bd** [comment]
That is the data that is in q3
