### ISSUE TITLE
Big_core - add CSR support part 1

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia#247]
Learn what CSR are.
Design the inferstucture - HW structs
Design a simple tests to read and write CSR.

**Comment by amichai-bd** [comment]
See here: https://riscv.org/technical/specifications/
Volume 1, Unprivileged Specification version 20191213  [[PDF](https://github.com/riscv/riscv-isa-manual/releases/download/Ratified-IMAFDQC/riscv-spec-20191213.pdf)]
Volume 2, Privileged Specification version 20211203  [[PDF](https://github.com/riscv/riscv-isa-manual/releases/download/Priv-v1.12/riscv-privileged-20211203.pdf)]

**Comment by danielk532** [comment]
Done together with @amichai-bd
