### ISSUE TITLE
tile - create correctly the next_tile_fifo_arb_id acording to the current tile! (not the next tile)

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia#272]
Use it in the mini_core_tile

The current override in the router is always looking at the next_tile_id to correctly define whech fifo_arb needs to allocated.
In the transaction from mini_core->router we need to figure out who is the correct fifo_arb to allocated according to the current tile_id (not next tile_id)

**Comment by yeonatanPerelman** [comment]
we can set this aside currently. Amichai, you said you will handle it @amichai-bd

**Comment by ShmuelSfez** [comment]
is this done @yeonatanPerelman ?
