### ISSUE TITLE
mem_ss - create the basic tb with rd/wr/ request tasks (d_mem/i_mem)

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia#287]
1) add basic RD/WR request to the mem_ss -> i_cache/d_cache
2) add trackers on the top-level interface -> what goes in, and out from core side and the FM side
3) create the "FM" behavioral to accept the RD/WR from the mem_ss

use the cache tb as a reference for all!!

**Comment by amichai-bd** [comment]
We can mark this as done once we have this sequence working with trackers:

From D_MEM side:
1) write to 5 CL in the same set. (force a dirty evict to FM) (with a 20 cycle delay between each write)
2) Read the 5 CL and make sure the data is as you wrote it. (with a 20 cycle delay between each read)

From I_MEM side:
1) We support only read, so to be able to validate this we must "backdoor" load the FM with some data
2) Send (with a 20 cycle delay between each read) - make sure it matches the Backdorr data

Note: 
1) Please don't overlap the address.
2) due to an issue in MC we can only use tq[0] - this is why we need the big delay.
3) no need to add delay (latency) between the mem_ss -> SRAM response at this point

**Comment by noamsabb** [comment]
Created test wr_rd_dmem with 5 write to differents CL same Set then 5 reads
Trackers look good i think, RD values are the ones we wrote 
![Capture d’écran 2023-06-21 à 21 46 23](https://github.com/amichai-bd/fpga_mafia/assets/83982485/79c3b3d4-d860-4fa5-ad07-cc095212416d)
