### ISSUE TITLE
BIG_CORE - button polar for high/low defualt 

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia#289]
![image](https://github.com/amichai-bd/fpga_mafia/assets/81047407/4c9756ce-efa4-4362-a8bb-12e36db8e6d1)
Please look at the reset signal that is connected to the Core.
As you can see its connect to "!KEY[0]" -> which means that the default read value of the button is '1' and only when pressed its '0'.

You should be able to tests this using a simple rvc_print_int on the button CR values.
Please let me know when you confirm this.

**Comment by danielk532** [comment]
Yes you are right. I confirmed it.
