### ISSUE TITLE
fabric - create a BP sequence.

### ISSUE THREAD

**Issue by ShmuelSfez** [amichai-bd/fpga_mafia#309]
force mini_core_ready to be 0, create 30-40 trans to fill all fifo's in the design. then release the mini_core_ready and see how the system reacts.

**Comment by ShmuelSfez** [comment]
show the a wave view of all fifo full indication of all fifo in path.

**Comment by ShmuelSfez** [comment]
sequence working correctly, now need to generalize it.
picture of waves:
![WhatsApp Image 2023-07-05 at 09 43 52](https://github.com/amichai-bd/fpga_mafia/assets/111231097/d0cf5d59-0122-4c82-b286-f35cb96176f8)

**Comment by amichai-bd** [comment]
@ShmuelSfez - looking at the fabric level0, I dont see param overrides. is that expected?
