### ISSUE TITLE
ROUTER - failing a test in the level0 "fifo_arb_back_pressure"

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia#310]
Failing this tests in the level0
Please review the tests, logs, waves and see if this is an RTL issue or verification issue
@yeonatanPerelman @ShmuelSfez 
``` 
python build.py -dut 'router' -debug -tests fifo_arb_back_pressure -hw -sim -params ' -gV_REQUESTS=10 -gV_FIFO_DEPTH=4 -gV_NUM_FIFO=4 -gV_MAX_DELAY=5 -gV_BACK_PRESSURE=1' 
```

**Comment by amichai-bd** [comment]
Please note: 
We had an RTL bug in the FIFO that we fixed last commit & PR:
We had the full indication set before the FIFO was actually full - we fixed it and its already In main

**Comment by ShmuelSfez** [comment]
i just pushed a fix.
