### ISSUE TITLE
router - re-code the  fifo & RR logic to the correct coding style

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia#84]
1. use the macros
2. Don't use an async reset
3. Use mean-terms
4. don't use reg/wire - only logic
5. interface - make sure to declare the type explicitly
6. remove all \<TABS\> from design!!!!! 
7. Use the Push/Pop terminology on the interface 
8. indentation!
9. Explicit signal width. ('0 is also acceptable)

**Comment by ShmuelSfez** [comment]
done wirh @amichai-bd
